# -*- coding: utf-8 -*-
"""Biagram

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dXfClUq_U790ma3lEfWSovytntxeu5pr
"""

import nltk
from nltk.util import ngrams
from nltk import word_tokenize

nltk.download('all')

s='National Science Day is celebrated on 28th February every year. The day is to commemorate the famous Indian Physicist Sir C.V. Raman’s discovery of the ‘Raman Effect.’ Moreover, Science Day is a day where people can learn about science and its impact on our lives. It can also be a way to get children excited about science and what they might want to do in the future. On Science Day, different events worldwide promote science and give people the opportunity to participate in hands-on experiments. BYJU’S essay on Science Day helps us know some notable achievements and the objectives of celebrating Science Day. The wonder of science is immeasurable, and we must respect the significant innovations. Science Day is an annual celebration of science and technology in India. National Science Day was first observed in 1987 in India. Moreover, Science Day is celebrated across the country in different sectors like schools, colleges, government offices, universities, etc. National Science Day is also celebrated in research institutes, medical colleges, and science institutes. Now, let us learn some objectives of celebrating Science Day by reading an essay on Science Day in English. Science Day is celebrated to spread awareness and a message about the importance of scientific theories and applications in everyday life. Science day essay in English explains to us, in brief, the objectives of celebrating Science Day. The objective of celebrating Science Day is to display the efforts, accomplishments and activities in the scientific field for human welfare. Moreover, science enthusiasts and scientists discuss theories of science in everyday life and methods to improve technologies.'

import re 
def generate_ngrams(s,n):
  s=re.sub(r'[^a-zA-Z0-9\s]','',s)
  s=s.lower()
  tokens=[token for token in s.split(" ") if token !=""]
  ngrams=zip(*[tokens[i:]for i in range(n)])
  return [" ".join(ngram) for ngram in ngrams],s
bigram,s=generate_ngrams(s,n=2)

print(bigram)

fdist=nltk.FreqDist(bigram)
print(fdist)
word_freq_pairs=[]
for k,v in fdist.items():
  word_freq_pairs.append((k.split()[0],k.split()[1],v))

word_freq_pairs[:5]

#co-occurance matrix
import pandas as pd
def bigran_frequency_dataframe (bigram_freq_pairs):
  words = sorted(set([pair[0] for pair in bigram_freq_pairs] + [pair[1] for pair in bigram_freq_pairs]))
  df = pd.DataFrame(columns=words, index=words)
  for pair in bigram_freq_pairs:
    df.at[pair[0], pair[1]] = pair[2]
  df.fillna(0, inplace=True)
  return df

df = bigran_frequency_dataframe (word_freq_pairs)

df.head()

number_of_bigrams = len(bigram)

science_count = s.count('science')
print (f'Number of times Science occurs: {science_count}')

bg_count = bigram.count ("science day")
print(f' Number of times bigram (science day) occurs: {bg_count}')
print (f"probabily of ‘day’ given ‘science’ P(bigram | science): {bg_count/science_count:.3f}")
print(f'probabilty of bigram in text : {bg_count/number_of_bigrams:.3f}')

import numpy as np
bigran_matrix = np.array(df)
target_word = 'science'

def Find_next_word_MLE(matrix, s, target_word):
  target_row = matrix[df.index.to_list().index(target_word), :]
  max_index = np.argmax(target_row)
  return df.index.to_list()[max_index]

for target_word in s.split():
  next_word = Find_next_word_MLE(bigran_matrix, s, target_word)
  print (f"{target_word} --> {next_word}")

